# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_log(object):
    def setupUi(self, log):
        log.setObjectName("log")
        log.resize(289, 186)
        log.setStyleSheet("")
        self.label = QtWidgets.QLabel(log)
        self.label.setGeometry(QtCore.QRect(40, 30, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(0, 170, 255)")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(log)
        self.lineEdit.setGeometry(QtCore.QRect(60, 80, 171, 20))
        self.lineEdit.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lineEdit.setObjectName("lineEdit")
        self.loginbtn = QtWidgets.QPushButton(log)
        self.loginbtn.setGeometry(QtCore.QRect(100, 120, 75, 24))
        self.loginbtn.setStyleSheet("background-color:rgb(149, 255, 28)")
        self.loginbtn.setObjectName("loginbtn")

        self.loginbtn.clicked.connect(self.)

        self.retranslateUi(log)
        QtCore.QMetaObject.connectSlotsByName(log)

    def retranslateUi(self, log):
        _translate = QtCore.QCoreApplication.translate
        log.setWindowTitle(_translate("log", "Form"))
        self.label.setText(_translate("log", "    Enter Password of MySql"))
        self.loginbtn.setText(_translate("log", "LOGIN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    log = QtWidgets.QWidget()
    ui = Ui_log()
    ui.setupUi(log)
    log.show()
    sys.exit(app.exec_())
